routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', [App\Http\Controllers\ClienteController::class, 'index'])->name('index');

/** Rotas de clientes **/
Route::group(['prefix' => 'cliente', 'as' => 'cliente.'], function () {
    Route::get('/', [App\Http\Controllers\ClienteController::class, 'index'])->name('index');
    Route::post('/', [App\Http\Controllers\ClienteController::class, 'store'])->name('store');
    Route::get('/create', [App\Http\Controllers\ClienteController::class, 'create'])->name('create');
    Route::get('/{id}', [App\Http\Controllers\ClienteController::class, 'show'])->name('show');
    Route::get('/{noticia}/edit', [App\Http\Controllers\ClienteController::class, 'edit'])->name('edit');
    Route::patch('/{id}', [App\Http\Controllers\ClienteController::class, 'update'])->name('update');
    Route::delete('/{id}', [App\Http\Controllers\ClienteController::class, 'destroy'])->name('destroy');
});

app/Models/Cliente.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    use HasFactory;
    protected $table = 'clientes';

    protected $fillable = [
        'id',
        'nome',
        'data_nascimento',
        'sexo',
        'cep',
        'endereco',
        'numero',
        'bairro',
        'cidade',
        'estado'
     ];

     public function setDataNascimentoAttribute($valor){
        $this->attributes['data_nascimento'] = date('Y-m-d', strtotime($valor));  
    }

    public function getDataNascimentoAttribute($value)
    {
        return date('d/m/Y', strtotime($value));
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Cliente;
use App\Http\Requests\ClienteFormRequest;

class ClienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $dados['clientes'] = Cliente::paginate(10);
        } catch (\Exception $exception) {
            //dd($exception);
            return redirect()->back()->withErrors('Não foi possível listar os Clientes');
        }

        return view('cliente.index', $dados);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cliente.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ClienteFormRequest $request)
    {
        try {
            $values = $request->validated();
            Cliente::create($values);
        } catch (\Exception $exception) {
            return redirect()->back()->withErrors('Não foi possível criar um Cliente');
        }

        return redirect()->route('cliente.index')->with('reponse', 'Sucesso ao criar o Cliente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $dados['cliente'] = Cliente::findOrFail($id);
        } catch (\Exception $exception) {
            return redirect()->back()->withErrors('Não foi possível deletar o Cliente');
        }

        return view('cliente.update', $dados);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ClienteFormRequest $request, $id)
    {
        try {
            $dat = (object)$request->validated();
            $enquete = Cliente::findOrFail($id);
            $enquete->fill(['nome' => $dat->nome]);
            $enquete->fill(['sexo' => $dat->sexo]);
            $enquete->fill(['data_nascimento' => $dat->data_nascimento]);
            $enquete->fill(['cep' => $dat->cep]);
            $enquete->fill(['endereco' => $dat->endereco]);
            $enquete->fill(['numero' => $dat->numero]);
            $enquete->fill(['bairro' => $dat->bairro]);
            $enquete->fill(['cidade' => $dat->cidade]);
            $enquete->fill(['estado' => $dat->estado]);
            $enquete->save();
        } catch (\Exception $exception) {
            dd($exception);
            return redirect()->back()->withErrors('Não foi possível criar um Cliente');
        }

        return redirect()->route('cliente.index')->with('reponse', 'Sucesso ao criar o Cliente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $cliente = Cliente::findOrFail($id);
            $cliente->delete();
        } catch (\Exception $exception) {
            return redirect()->back()->withErrors('Não foi possível deletar o Cliente');
        }

        return redirect()->route('cliente.index')->with('reponse', 'Sucesso ao deletar o Cliente');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/cliente/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Cadastrar Cliente
                    <a href="{{route('cliente.index')}}" title="Voltar" class="btn btn-primary btn-sm float-right"><i class="fas fa-arrow-left"></i> </a>&nbsp;
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('cliente.store') }}" class="needs-validation" autocomplete="off">
                        @csrf

                        {!!Form::text('nome', 'Nome')!!}
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                {!!Form::text('data_nascimento', 'Data de Nascimento')->attrs(['class' => 'data_nascimento'])!!}
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                {!!Form::select('sexo', 'Sexo', ['' => 'Selecione um sexo', 'M' => 'Masculino', 'F' => 'Feminino'])!!}
                            </div>
                        </div>
                        {!!Form::text('cep', 'CEP')->attrs(['class' => 'cep'])->required(false) !!}
                        <div class="row">
                            <div class="col-lg-8 col-md-6 col-sm-12 col-xs-12">
                            {!!Form::text('endereco', 'Endereço')->attrs(['class' => 'logradouro'])->required(false)!!}
                            </div>
                            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                                {!!Form::text('numero', 'Número')->required(false)!!}
                            </div>
                        </div>
                        {!!Form::text('bairro', 'Bairro')->attrs(['class' => 'bairro'])->required(false)!!}
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                {!!Form::text('cidade', 'Cidade')->attrs(['class' => 'cidade'])->required(false)!!}
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                {!!Form::text('estado', 'Estado')->attrs(['class' => 'uf'])->required(false)!!}
                            </div>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary float-right">
                                Salvar
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
    <!--<script src="{{asset('js/base.js')}}"></script>-->
    <script src="{{ asset('js/jquery.mask.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('.cep').mask('00000-000');
            $('.data_nascimento').mask('00/00/0000');
        });
    </script>
    <script src="{{ asset('js/buscaCep.js') }}"></script>
@endsection

resources/views/cliente/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    Lista de Clientes
                </div>

                <div class="card-body">
                    <div class="box-cad float-right">
                        <a href="{{route('cliente.create')}}" title="Cadastrar" class="btn btn-success">Cadastrar</a>
                    </div>
                    <table class="table">
                        <thead>
                            <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Nome</th>
                            <th scope="col">Data de Nascimento</th>
                            <th scope="col">Sexo</th>
                            <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($clientes as $cliente)
                                <tr>
                                    <th scope="row">{{$cliente->id}}</th>
                                    <td>{{$cliente->nome}}</td>
                                    <td>{{$cliente->data_nascimento}}</td>
                                    <td>{{$cliente->sexo == 'M' ? 'Masculino' : 'Feminino'}}</td>
                                    <td>
                                        <a href="{{route('cliente.edit', $cliente->id)}}" title="Alterar" class="btn btn-primary btn-sm">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        <button data-toggle="modal" data-target="#clienteDelete"
                                                data-cliente-id="{{$cliente->id}}"
                                                data-cliente-nome="{{$cliente->nome}}"
                                                class="btn btn-danger btn-sm" type="button" title="Deletar">
                                            <i class="fas fa-trash-alt"></i>
                                        </button>
                                    </td>
                                </tr>
                            @empty
                                <tr style="text-align: center">
                                    <td colspan="4">Nenhum registro cadastrado no momento.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                    <div class="box-pagination">{{$clientes->links("pagination::bootstrap-4")}}</div>
                </div>
            </div>
        </div>
    </div>
</div>
@include('cliente.modals.delete')

@endsection


@section('js')
    <script src="{{ asset('js/cliente/modals/delete.js') }}"></script>
@endsection

resources/views/cliente/modals/create-juridico.blade.php
<div class="modal fade" id="pessoaJuridicoCreate">
    <form method="POST" id="pessoaJuridicoCreateForm" action="{{route('cliente.store')}}" enctype="multipart/form-data" class="needs-validation" autocomplete="off" novalidate>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Cadastrar Cliente Jurídico</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    @csrf
                    <input name="tipo" type="hidden" value="Jurídico" />
                    <div class="form-group">
                        <label>Razao Social</label>
                        <input value="{{old('razao_social')}}" type="text" name="razao_social" required
                               class="form-control @error('razao_social') is-invalid @enderror">
                        <div class="invalid-feedback">Obrigatório</div>
                    </div>
                    <div class="form-group">
                        <label>Nome Fantasia</label>
                        <input value="{{old('nome')}}" type="text" name="nome" required
                               class="form-control @error('nome') is-invalid @enderror">
                        <div class="invalid-feedback">Obrigatório</div>
                    </div>
                    <div class="form-group">
                        <label>E-mail</label>
                        <input value="{{old('email')}}" type="email" name="email" required
                               class="form-control @error('email') is-invalid @enderror">
                        <div class="invalid-feedback">Obrigatório</div>
                    </div>
                    <div class="form-group">
                        <label>CNPJ</label>
                        <input value="{{old('cnpj')}}" type="text" name="cnpj" required
                               class="form-control cnpj @error('cnpj') is-invalid @enderror">
                        <div class="invalid-feedback">Obrigatório</div>
                    </div>
                    <div class="form-group">
                        <label>CEP</label>
                        <input value="{{old('cep')}}" type="text" name="cep" required
                               class="form-control cep @error('cep') is-invalid @enderror">
                        <div class="invalid-feedback">Obrigatório</div>
                    </div>
                    <div class="form-group">
                        <label>Endereço</label>
                        <input value="{{old('logradouro')}}" type="text" name="logradouro"
                               class="form-control logradouro @error('logradouro') is-invalid @enderror">
                    </div>
                    <div class="form-group">
                        <label>Número</label>
                        <input value="{{old('numero')}}" type="text" name="numero"
                               class="form-control @error('numero') is-invalid @enderror">
                    </div>
                    <div class="form-group">
                        <label>Bairro</label>
                        <input value="{{old('bairro')}}" type="text" name="bairro"
                               class="form-control bairro @error('bairro') is-invalid @enderror">
                    </div>
                    <div class="form-group">
                        <label>Cidade</label>
                        <input value="{{old('cidade')}}" type="text" name="cidade"
                               class="form-control cidade @error('cidade') is-invalid @enderror">
                    </div>
                    <div class="form-group">
                        <label>Estado</label>
                        <input value="{{old('estado')}}" type="text" name="estado"
                               class="form-control uf @error('estado') is-invalid @enderror">
                    </div>
                    <div class="form-group @error('image') has-error @enderror">
                        <label for="exampleInputFile">Imagem</label>
                        <div class="input-group">
                            <div class="custom-file">
                                <input type="file" name="image" class="custom-file-input" id="exampleInputFile">
                                <label class="custom-file-label" for="exampleInputFile">Selecione</label>
                            </div>
                        </div>
                        <a href="" class="box-img" id="uempresa-a-image" data-toggle="lightbox" data-gallery="example-gallery" title="Visualizar" >
                            <img src="" id="uempresa-image" class="img-fluid" width="100" />
                        </a>
                    </div>

                </div>
                <div class="modal-footer justify-content-between">
                    <button type="submit" class="btn btn-success btn-sm"><i class="fas fa-plus"></i> Cadastrar</button>
                    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
    </form>
    <!-- /.modal-dialog -->
</div>

resources/views/cliente/modals/delete.blade.php
<div class="modal fade" id="clienteDelete">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="clienteDeleteForm" action="" method="POST" class="needs-validation" novalidate>
                @csrf
                @method("DELETE")

                <div class="modal-header card-header-danger">
                    <h4 class="modal-title">Deletar Cliente</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Você tem certeza que deseja deletar o Cliente <span class="font-weight-bold text-danger" id="dcliente-nome"></span>?
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="submit" class="btn btn-danger btn-sm">Deletar</button>
                    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancelar</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/cliente/modals/update.blade.php
<div class="modal fade" id="clienteUpdate" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <form id="clienteFisicoUpdateForm" action="" method="POST" enctype="multipart/form-data" class="needs-validation" novalidate>
                <div class="modal-header">
                    <h4 class="modal-title">Alterar Cliente Físico</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    @csrf
                    @method("PATCH")
                    <input name="tipo" type="hidden" value="Físico" />
                    <div class="form-group">
                        <label>Nome</label>
                        <input value="{{old('nome')}}" id="ucliente-fisico-nome" type="text" name="nome" required
                               class="form-control @error('nome') is-invalid @enderror">
                        <div class="invalid-feedback">Obrigatório</div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>E-mail</label>
                                <input value="{{old('email')}}" id="ucliente-fisico-email" type="email" name="email" required
                                       class="form-control @error('email') is-invalid @enderror">
                                <div class="invalid-feedback">Obrigatório</div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>CPF</label>
                                <input value="{{old('cpf')}}" id="ucliente-fisico-cpf" type="text" name="cpf" required
                                       class="form-control cpf @error('cpf') is-invalid @enderror">
                                <div class="invalid-feedback">Obrigatório</div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>CEP</label>
                        <input value="{{old('cep')}}" id="ucliente-fisico-cep" type="text" name="cep" required
                               class="form-control cep @error('cep') is-invalid @enderror">
                        <div class="invalid-feedback">Obrigatório</div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Endereço</label>
                                <input value="{{old('logradouro')}}" id="ucliente-fisico-logradouro" type="text" name="logradouro"
                                       class="form-control logradouro @error('logradouro') is-invalid @enderror">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Número</label>
                                <input value="{{old('numero')}}" id="ucliente-fisico-numero" type="text" name="numero"
                                       class="form-control @error('numero') is-invalid @enderror">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Bairro</label>
                        <input value="{{old('bairro')}}" id="ucliente-fisico-bairro" type="text" name="bairro"
                               class="form-control bairro @error('bairro') is-invalid @enderror">
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Cidade</label>
                                <input value="{{old('cidade')}}" id="ucliente-fisico-cidade" type="text" name="cidade"
                                       class="form-control cidade @error('cidade') is-invalid @enderror">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Estado</label>
                                <input value="{{old('estado')}}" id="ucliente-fisico-estado" type="text" name="estado"
                                       class="form-control uf @error('estado') is-invalid @enderror">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Telefone</label>
                                <input value="{{old('telefone')}}" id="ucliente-fisico-telefone" type="text" name="telefone"
                                       class="form-control telefone @error('telefone') is-invalid @enderror">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label><i class="fab fa-whatsapp"></i> Celular</label>
                                <input value="{{old('celular')}}" id="ucliente-fisico-celular" type="text" name="celular"
                                       class="form-control celular @error('celular') is-invalid @enderror">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label><i class="fab fa-instagram"></i> Instagram</label>
                                <input value="{{old('instagram')}}" id="ucliente-fisico-instagram" type="text" name="instagram"
                                       class="form-control @error('instagram') is-invalid @enderror">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label><i class="fab fa-facebook"></i> Facebook</label>
                                <input value="{{old('facebook')}}" id="ucliente-fisico-facebook" type="text" name="facebook"
                                       class="form-control @error('facebook') is-invalid @enderror">
                            </div>
                        </div>
                    </div>
                    <!--<div class="form-group @error('image') has-error @enderror">
                        <label for="exampleInputFile">Imagem</label>
                        <div class="input-group">
                            <div class="custom-file">
                                <input type="file" name="image" class="custom-file-input" id="exampleInputFile">
                                <label class="custom-file-label" for="exampleInputFile">Selecione</label>
                            </div>
                        </div>
                        <a href="" class="box-img" id="uempresa-a-image" data-toggle="lightbox" data-gallery="example-gallery" title="Visualizar" >
                            <img src="" id="uempresa-image" class="img-fluid" width="100" />
                        </a>
                    </div>-->

                </div>
                <div class="modal-footer justify-content-between">
                    <button type="submit" class="btn btn-primary btn-sm">Alterar</button>
                    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancelar</button>
                </div>
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection